# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorregirInformacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correccionInfo', models.TextField()),
                ('justificacionInfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enciclopedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMovimiento', models.CharField(max_length=30)),
                ('creador', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='movimientos')),
                ('categoria', models.CharField(choices=[('Isolations', 'Isolations'), ('Twirls', 'Twirls'), ('One-Handed Cuts', 'One-Handed Cuts'), ('One-Handed Fans', 'One-Handed Fans'), ('Grips', 'Grips'), ('Spreads', 'Spreads'), ('Two-Handed Fans', 'Two-Handed Fans'), ('Utilities', 'Utilities'), ('Two-Handed Cuts', 'Two-Handed Cuts'), ('Shuffles', 'Shuffles')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagenGaleria', models.ImageField(upload_to='galeria')),
            ],
        ),
        migrations.CreateModel(
            name='IdentificarMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkVideo', models.URLField(max_length=100)),
                ('minuto', models.IntegerField()),
                ('segundo', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('nombreIMovimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Card.Enciclopedia')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoP', models.CharField(max_length=50)),
                ('apellidoM', models.CharField(blank=True, max_length=50)),
                ('tiempoPracticando', models.DateTimeField(blank=True, null=True)),
                ('movimientosFavoritos', models.TextField()),
                ('movimientosOriginales', models.TextField()),
                ('imagen', models.ImageField(upload_to='fotos_perfil')),
                ('ciudad', models.CharField(max_length=35)),
                ('correo', models.CharField(max_length=50)),
                ('youtube', models.URLField(blank=True, max_length=100)),
                ('instagram', models.URLField(blank=True, max_length=100)),
                ('reddit', models.URLField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReordenacionMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correccionMov', models.TextField()),
                ('justificacionMov', models.TextField()),
                ('nombreRMovimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Card.Enciclopedia')),
            ],
        ),
        migrations.AddField(
            model_name='corregirinformacion',
            name='nombreCMovimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Card.Enciclopedia'),
        ),
    ]
