# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enciclopedia',
            name='categoria',
            field=models.CharField(choices=[('Isolations', 'Isolations'), ('Twirls', 'Twirls'), ('Utilities', 'Utilities'), ('One-Handed Cuts', 'One-Handed Cuts'), ('Grips', 'Grips'), ('One-Handed Fans', 'One-Handed Fans'), ('Spreads', 'Spreads'), ('Two-Handed Fans', 'Two-Handed Fans'), ('Two-Handed Cuts', 'Two-Handed Cuts'), ('Shuffles', 'Shuffles')], max_length=16),
        ),
    ]
