# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0002_auto_20171130_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarioRetro', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='enciclopedia',
            name='categoria',
            field=models.CharField(choices=[('Two-Handed Fans', 'Two-Handed Fans'), ('One-Handed Cuts', 'One-Handed Cuts'), ('One-Handed Fans', 'One-Handed Fans'), ('Twirls', 'Twirls'), ('Spreads', 'Spreads'), ('Grips', 'Grips'), ('Shuffles', 'Shuffles'), ('Utilities', 'Utilities'), ('Two-Handed Cuts', 'Two-Handed Cuts'), ('Isolations', 'Isolations')], max_length=16),
        ),
    ]
